### ISSUE TITLE
Pending orders Klarnakp payment method  can not be cancelled manually or by cron.

### ISSUE THREAD

**Issue by kaplansin** [buckaroo-it/Magento2#654]

**Comment by kaplansin** [comment]
- Create an order by selecting Klarna Payment method. Order will be created as New/pending status on magento
- At payment gateway page, do not take any action, just close the window.
- Order will remain as new/pending state/status as expected.
- When you try to cancel order manually, you will receive  following exception.
`report.CRITICAL: SoapFault exception: [Client] Structure validation of XML failed. The SOAP request structure does not conform to the specification. in /project/vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php:197`
for full stack trace
`[2023-01-10T12:28:51.409712+00:00] report.CRITICAL: SoapFault exception: [Client] Structure validation of XML failed. The SOAP request structure does not conform to the specification. in /project/vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php:197
Stack trace:
#0 /project/vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php(197): SoapClient->__soapCall()
#1 /project/vendor/magento/module-payment/Gateway/Http/Client/Soap.php(75): Buckaroo\Magento2\Soap\Client\SoapClientWSSEC->__soapCall()
#2 /project/vendor/buckaroo/magento2/Gateway/Http/Bpe3.php(217): Magento\Payment\Gateway\Http\Client\Soap->placeRequest()
#3 /project/vendor/buckaroo/magento2/Gateway/Http/Bpe3.php(154): Buckaroo\Magento2\Gateway\Http\Bpe3->doRequest()
#4 /project/vendor/buckaroo/magento2/Model/Method/AbstractMethod.php(1331): Buckaroo\Magento2\Gateway\Http\Bpe3->void()
#5 /project/generated/code/Buckaroo/Magento2/Model/Method/Klarnakp/Interceptor.php(392): Buckaroo\Magento2\Model\Method\AbstractMethod->voidTransaction()
#6 /project/vendor/buckaroo/magento2/Model/Method/AbstractMethod.php(1309): Buckaroo\Magento2\Model\Method\Klarnakp\Interceptor->voidTransaction()
#7 /project/generated/code/Buckaroo/Magento2/Model/Method/Klarnakp/Interceptor.php(383): Buckaroo\Magento2\Model\Method\AbstractMethod->void()
#8 /project/vendor/buckaroo/magento2/Model/Method/AbstractMethod.php(1247): Buckaroo\Magento2\Model\Method\Klarnakp\Interceptor->void()
#9 /project/generated/code/Buckaroo/Magento2/Model/Method/Klarnakp/Interceptor.php(374): Buckaroo\Magento2\Model\Method\AbstractMethod->cancel()
#10 /project/vendor/magento/module-sales/Model/Order/Payment.php(1277): Buckaroo\Magento2\Model\Method\Klarnakp\Interceptor->cancel()
#11 /project/vendor/magento/module-sales/Model/Order/Payment.php(895): Magento\Sales\Model\Order\Payment->_void()
#12 /project/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(248): Magento\Sales\Model\Order\Payment->cancel()
#13 /project/vendor/magento/module-sales/Model/Order.php(1278): Magento\Sales\Model\Order\Payment\Interceptor->cancel()
#14 /project/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->cancel()
#15 /project/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent()
#16 /project/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#17 /project/generated/code/Magento/Sales/Model/Order/Interceptor.php(383): Magento\Sales\Model\Order\Interceptor->___callPlugins()
#18 /project/vendor/magento/module-sales/Model/Service/OrderService.php(109): Magento\Sales\Model\Order\Interceptor->cancel()
#19 /project/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->cancel()
#20 /project/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent()
#21 /project/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}()
#22 /project/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(23): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins()
#23 /project/vendor/magento/module-sales/Controller/Adminhtml/Order/Cancel.php(35): Magento\Sales\Model\Service\OrderService\Interceptor->cancel()
#24 /project/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Cancel->execute()
#25 /project/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callParent()
#26 /project/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#27 /project/generated/code/Magento/Sales/Controller/Adminhtml/Order/Cancel/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callPlugins()
#28 /project/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->execute()
#29 /project/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#30 /project/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#31 /project/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callParent()
#32 /project/vendor/weltpixel/m2-weltpixel-backend/src/Plugin/Utility.php(73): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#33 /project/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#34 /project/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#35 /project/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#36 /project/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#37 /project/generated/code/Magento/Sales/Controller/Adminhtml/Order/Cancel/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callPlugins()
#38 /project/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->dispatch()
#39 /project/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#40 /project/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#41 /project/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#42 /project/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#43 /project/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#44 /project/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#45 /project/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#46 /project/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#47 /project/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#48 /project/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#49 {main} [] []
[2023-01-10T12:28:51.809979+00:00] report.INFO: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header.inner.right' and 'header' respectively. [] []

`

**Comment by Buckaroo-Rens** [comment]
@kaplansin Thanks for informing us about this. We will do some additional research. Can you maybe share with us what version of the Buckaroo Plugin version your using and on what Magento version? Thank you in advance.

**Comment by kaplansin** [comment]
Hi @Buckaroo-Rens 

Magento Version : 2.4.4-p2
Buckaroo Plugin : v1.44.0

**Comment by Buckaroo-Rens** [comment]
@kaplansin thanks :)

**Comment by kaplansin** [comment]
Hi @Buckaroo-Rene 
Yes we are using **Klarna Pay later (authorize/capture)**

**Comment by Buckaroo-Rene** [comment]
@kaplansin ,

Thank you for the confimation. We've logged a ticket for it is scheduled in sprint 1 (start 10-1 and lasts untill 24-01).
We'll let you know when we have more information regarding this issue.

**Comment by kaplansin** [comment]
HI @Buckaroo-Rene  
Do you have any update?

**Comment by Buckaroo-Rene** [comment]
@kaplansin ,
Sorry for the late reply on this case. We've checked this and:
The pending Klarna transactions should automatically get a cancelled state by a build in cron job.
The cron is runned every 6 hours and updates the previous 7 days from the config due date.
If the Buckaroo Plaza gets a cancellation from Klarna earlier, then this will be send with a push message to set the order on cancelled as well.

There is no cancellation request for a authorize/reservation, so that's why the order can't be cancelled manually.
Does the orders get updated for you as well withing the 6 hours? And is this something you can work with?
